version: '3.8'
services:
        database:
                restart: always
                container_name: postgres
                image: postgres:latest
                #restart: always
                environment:
                        POSTGRES_USER: contact
                        POSTGRES_PASSWORD: 12345perro1998
                        POSTGRES_HOST_AUTH_METHOD: password
                        #POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd -d postgres
                ports:
                        - 9001:5432
                volumes:
                        - db_volume:/var/lib/postgresql
                          #                        - ./init.sql:/docker-entrypoint-initdb.d/init.sh
        #engine:
                #restart: always
                #container_name: engine_app
                #build: engine.py

        web-site:
                restart: always
                container_name: flask_app
                build: .
                volumes:
                        - .:/usr/src/app
                ports:
                        - 9000:8999
                depends_on:
                        - database
        jenkins:
                image: jenkins/jenkins:lts
                privileged: true
                user: root
                ports:
                        - 8081:8080
                        - 9500:50000
                container_name: jenkins
                volumes:
                        - ~/jenkins:/var/jenkins_home
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /usr/local/bin/docker:/usr/local/bin/docker
volumes:
        db_volume:
